spring:
  main:
    log-startup-info: false
  datasource:
    url: 'jdbc:mysql://127.0.0.1:3306/spring-book'
    username: 'root'
    password: ''
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
server:
  port: 8088

mybatis:
  mapper-locations: 'classpath:mapper/*.xml'
#  mapper-locations: 'classpath:cn/org/springbook/book/mapper/BookMapper.xml'
